// Erzeugt lib/l10n/generated/*.g.dart aus l10n/languages.json
//   dart run tool/generate_language_registry.dart

import 'dart:convert';
import 'dart:io';

void main() {
  final root = Directory.current;
  final registryFile = File('${root.path}/l10n/languages.json');
  if (!registryFile.existsSync()) {
    stderr.writeln('Fehlt: ${registryFile.path}');
    exitCode = 1;
    return;
  }

  final registry =
      jsonDecode(registryFile.readAsStringSync()) as Map<String, dynamic>;
  final languages = (registry['languages'] as List)
      .cast<Map<String, dynamic>>();
  final excludeFromMenu = (registry['excludeFromMenu'] as List?)
          ?.map((e) => e.toString())
          .toSet() ??
      {};

  final l10nDir = Directory('${root.path}/lib/l10n');
  final dartFiles = l10nDir
      .listSync()
      .whereType<File>()
      .where((f) => RegExp(r'app_localizations_[a-z]{2,3}\.dart$')
          .hasMatch(f.uri.pathSegments.last))
      .map((f) => f.uri.pathSegments.last)
      .toList();

  String classSuffix(String code) {
    if (code.length == 2) return code.toUpperCase();
    return code[0].toUpperCase() + code.substring(1).toLowerCase();
  }

  final menuLanguages = <Map<String, dynamic>>[];
  final codes = <String>[];
  final intlByCode = <String, String>{};
  final hour12Codes = <String>[];
  final timeSuffixByCode = <String, String>{};
  final timeStyleByCode = <String, String>{};

  for (final e in languages) {
    final code = (e['code'] as String?)?.trim();
    final intl = (e['intl_locale'] as String?)?.trim();
    if (code == null || code.isEmpty || intl == null || intl.isEmpty) {
      continue;
    }
    intlByCode[code] = intl;
    timeSuffixByCode[code] = (e['time_suffix'] as String?) ?? '';
    timeStyleByCode[code] =
        (e['time_style'] as String?)?.trim() ?? 'colon_suffix';
    if (e['hour12'] == true) {
      hour12Codes.add(code);
    }
    if (e['appMenu'] == false) continue;
    codes.add(code);
    menuLanguages.add(e);
  }

  final outDir = Directory('${root.path}/lib/l10n/generated');
  outDir.createSync(recursive: true);

  // --- language_registry.g.dart ---
  final regBuf = StringBuffer()
    ..writeln('// GENERATED by tool/generate_language_registry.dart')
    ..writeln('// Quelle: l10n/languages.json — intl_locale für Datum/Uhrzeit (package:intl).')
    ..writeln('// Nicht von Hand ändern. Sync: node scripts/sync-language-registry.js')
    ..writeln()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..writeln('/// Zentrale Sprachliste (App-Menü + Locale).')
    ..writeln('abstract final class LanguageRegistry {')
    ..writeln('  static const List<String> supportedLanguageCodes = [');
  for (final c in codes) {
    regBuf.writeln("    '$c',");
  }
  regBuf.writeln('  ];');
  regBuf.writeln();
  regBuf.writeln('  static const List<Locale> materialLocales = [');
  for (final c in codes) {
    if (c == 'tr') {
      regBuf.writeln("    Locale('tr', ''),");
    } else {
      regBuf.writeln("    Locale('$c'),");
    }
  }
  regBuf.writeln('  ];');
  regBuf.writeln();
  regBuf.writeln('  static const Map<String, String> intlLocaleByCode = {');
  for (final e in intlByCode.entries) {
    regBuf.writeln("    '${e.key}': '${e.value}',");
  }
  regBuf.writeln('  };');
  regBuf.writeln();
  regBuf.writeln('  /// BCP-47 für [DateFormat] / Intl (z. B. vi → vi-VN).');
  regBuf.writeln("  static String intlTagFor(String languageCode) {");
  regBuf.writeln('    return intlLocaleByCode[languageCode] ?? languageCode;');
  regBuf.writeln('  }');
  regBuf.writeln();
  regBuf.writeln('  /// 12-Stunden-Uhr (nur Sprachen mit hour12 in languages.json, z. B. en).');
  regBuf.writeln('  static const Set<String> hour12LanguageCodes = {');
  for (final c in hour12Codes) {
    regBuf.writeln("    '$c',");
  }
  regBuf.writeln('  };');
  regBuf.writeln();
  regBuf.writeln('  static bool usesHour12(String languageCode) {');
  regBuf.writeln('    return hour12LanguageCodes.contains(languageCode);');
  regBuf.writeln('  }');
  regBuf.writeln();
  regBuf.writeln('  /// Text nach der Uhrzeit (z. B. DE „ Uhr“, FR/ES/PT „ h“, sonst leer).');
  regBuf.writeln('  /// Quelle: [time_suffix] in l10n/languages.json.');
  regBuf.writeln('  static const Map<String, String> timeSuffixByCode = {');
  for (final e in timeSuffixByCode.entries) {
    regBuf.writeln("    '${e.key}': '${e.value.replaceAll("'", r"\'")}',");
  }
  regBuf.writeln('  };');
  regBuf.writeln();
  regBuf.writeln('  static String timeSuffixFor(String languageCode) {');
  regBuf.writeln('    return timeSuffixByCode[languageCode] ?? \'\';');
  regBuf.writeln('  }');
  regBuf.writeln();
  regBuf.writeln('  /// Uhrzeit-Layout: colon_suffix | fr_h | h_compact | ja_kanji | intl_12');
  regBuf.writeln('  static const Map<String, String> timeStyleByCode = {');
  for (final e in timeStyleByCode.entries) {
    regBuf.writeln("    '${e.key}': '${e.value}',");
  }
  regBuf.writeln('  };');
  regBuf.writeln();
  regBuf.writeln('  static String timeStyleFor(String languageCode) {');
  regBuf.writeln(
    "    return timeStyleByCode[languageCode] ?? 'colon_suffix';",
  );
  regBuf.writeln('  }');
  regBuf.writeln('}');

  File('${outDir.path}/language_registry.g.dart')
      .writeAsStringSync('${regBuf.toString()}\n');

  // --- locale_translations.g.dart (nur vorhandene app_localizations_XX.dart) ---
  final importLines = <String>{};
  final cases = <String>[];
  for (final e in menuLanguages) {
    final code = e['code'] as String;
    final suffix = classSuffix(code);
    final fileName = 'app_localizations_$code.dart';
    if (!dartFiles.contains(fileName)) {
      stderr.writeln(
        'Warnung: $fileName fehlt — Übersetzungen für $code noch nicht importiert (dart run tool/import_l10n_from_arb.dart).',
      );
      continue;
    }
    importLines.add("import '../app_localizations_$code.dart';");
    cases.add("    '$code' => AppLocalizations$suffix.translations,");
  }
  importLines.add("import '../app_localizations_de.dart';");
  final sortedImports = importLines.toList()..sort();

  final trBuf = StringBuffer()
    ..writeln('// GENERATED by tool/generate_language_registry.dart')
    ..writeln('// Quelle: l10n/languages.json + vorhandene app_localizations_*.dart')
    ..writeln()
    ..writeln(sortedImports.join('\n'))
    ..writeln()
    ..writeln('Map<String, String> translationsForLanguageCode(String code) {')
    ..writeln('  return switch (code) {');
  for (final line in cases) {
    trBuf.writeln(line);
  }
  trBuf
    ..writeln("    _ => AppLocalizationsDE.translations,")
    ..writeln('  };')
    ..writeln('}');

  File('${outDir.path}/locale_translations.g.dart')
      .writeAsStringSync('${trBuf.toString()}\n');

  // --- language_menu_entries.g.dart (App-Sprachmenü + QR-Export) ---
  final menuRows = <Map<String, String>>[];
  for (final e in languages) {
    final code = (e['code'] as String?)?.trim();
    final name = (e['name'] as String?)?.trim();
    final flag = (e['flag'] as String?)?.trim();
    if (code == null || code.isEmpty || name == null || name.isEmpty) {
      continue;
    }
    if (e['appMenu'] == false || excludeFromMenu.contains(code)) continue;
    menuRows.add({
      'code': code,
      'name': name,
      'flag': flag ?? '',
    });
  }
  menuRows.sort(
    (a, b) => a['name']!.toLowerCase().compareTo(b['name']!.toLowerCase()),
  );

  final menuBuf = StringBuffer()
    ..writeln('// GENERATED by tool/generate_language_registry.dart')
    ..writeln('// Quelle: l10n/languages.json — App-Sprachmenü (Englische Namen + Flagge).')
    ..writeln('// Nicht von Hand ändern. Sync: node scripts/sync-language-registry.js')
    ..writeln()
    ..writeln('/// Eintrag für Popup-Menü / QR-Export-Sprache.')
    ..writeln('class LanguageMenuEntry {')
    ..writeln('  const LanguageMenuEntry({')
    ..writeln('    required this.code,')
    ..writeln('    required this.name,')
    ..writeln('    required this.flag,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String code;')
    ..writeln('  final String name;')
    ..writeln('  final String flag;')
    ..writeln()
    ..writeln("  Map<String, String> toMap() => {")
    ..writeln("    'code': code,")
    ..writeln("    'name': name,")
    ..writeln("    'flag': flag,")
    ..writeln('  };')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Alle App-Menü-Sprachen, alphabetisch nach englischem Namen.')
    ..writeln('abstract final class LanguageMenuEntries {')
    ..writeln('  static const List<LanguageMenuEntry> sorted = [');
  for (final row in menuRows) {
    final flag = row['flag']!.replaceAll("'", r"\'");
    menuBuf.writeln(
      "    LanguageMenuEntry(code: '${row['code']}', name: '${row['name']}', flag: '$flag'),",
    );
  }
  menuBuf
    ..writeln('  ];')
    ..writeln()
    ..writeln('  /// Sprachen pro Spalte (Menü: Spalte 1 Albanian…English, Spalte 2 French…).')
    ..writeln('  static const int rowsPerColumn = 5;')
    ..writeln()
    ..writeln('  /// Alphabetisch sortiert, in Spalten à [rowsPerColumn] (zeilenweise gefüllt).')
    ..writeln('  static List<List<LanguageMenuEntry>> get columns {')
    ..writeln('    final out = <List<LanguageMenuEntry>>[];')
    ..writeln('    for (var i = 0; i < sorted.length; i += rowsPerColumn) {')
    ..writeln('      final end = i + rowsPerColumn;')
    ..writeln('      out.add(sorted.sublist(i, end > sorted.length ? sorted.length : end));')
    ..writeln('    }')
    ..writeln('    return out;')
    ..writeln('  }')
    ..writeln()
    ..writeln('  static List<Map<String, String>> asMaps() =>')
    ..writeln('      sorted.map((e) => e.toMap()).toList(growable: false);')
    ..writeln('}');

  File('${outDir.path}/language_menu_entries.g.dart')
      .writeAsStringSync('${menuBuf.toString()}\n');

  stdout.writeln('Wrote ${outDir.path}/language_registry.g.dart');
  stdout.writeln('Wrote ${outDir.path}/locale_translations.g.dart');
  stdout.writeln('Wrote ${outDir.path}/language_menu_entries.g.dart');
}
