// Liest l10n/app_<locale>.arb und schreibt lib/l10n/app_localizations_<locale>.dart neu.
// Vorher mit BabelEdit bearbeitete .arb-Dateien committen, dann:
//   dart run tool/import_l10n_from_arb.dart
//
// Hinweis: Die generierten Dart-Dateien enthalten keine Kommentarblöcke mehr —
// Quelle der Wahrheit für Übersetzungen ist dann l10n/*.arb.

import 'dart:convert';
import 'dart:io';

/// Locale-Code → Suffix für `AppLocalizationsXX` (z. B. uk → UK).
String _classSuffixForLocale(String code) {
  if (code.length == 2) return code.toUpperCase();
  return code[0].toUpperCase() + code.substring(1).toLowerCase();
}

/// Alle `l10n/app_<locale>.arb` (ohne Vorlage).
Map<String, String> _discoverLocales(Directory arbDir) {
  final locales = <String, String>{};
  for (final f in arbDir.listSync().whereType<File>()) {
    final name = f.uri.pathSegments.last;
    final m = RegExp(r'^app_([a-z]{2,3})\.arb$').firstMatch(name);
    if (m == null) continue;
    final code = m.group(1)!;
    locales[code] = _classSuffixForLocale(code);
  }
  return locales;
}

void main() {
  final root = Directory.current;
  final arbDir = Directory.fromUri(root.uri.resolve('l10n/'));
  if (!arbDir.existsSync()) {
    stderr.writeln('Ordner fehlt: ${arbDir.path} — zuerst dart run tool/export_l10n_arb.dart');
    exitCode = 1;
    return;
  }

  final _locales = _discoverLocales(arbDir);
  if (_locales.isEmpty) {
    stderr.writeln('Keine l10n/app_<locale>.arb gefunden.');
    exitCode = 1;
    return;
  }

  final dePath = arbDir.uri.resolve('app_de.arb').toFilePath();
  final deFile = File(dePath);
  if (!deFile.existsSync()) {
    stderr.writeln('Datei fehlt: $dePath');
    exitCode = 1;
    return;
  }

  final allKeys = <String>{};
  final perLocale = <String, Map<String, String>>{};

  for (final code in _locales.keys) {
    final arbFile = File(arbDir.uri.resolve('app_$code.arb').toFilePath());
    if (!arbFile.existsSync()) {
      stderr.writeln('Warnung: fehlt $arbFile — überspringe $code');
      continue;
    }
    final raw = jsonDecode(arbFile.readAsStringSync()) as Map<String, dynamic>;
    final m = <String, String>{};
    for (final e in raw.entries) {
      final k = e.key;
      if (k == '@@locale' || k.startsWith('@')) continue;
      allKeys.add(k);
      final v = e.value;
      m[k] = v is String ? v : v?.toString() ?? '';
    }
    perLocale[code] = m;
  }

  final deMap = perLocale['de'] ?? {};
  // Reihenfolge: wie in app_de.arb (JSON-Reihenfolge), dann fehlende Keys alphabetisch
  final deRaw = jsonDecode(deFile.readAsStringSync()) as Map<String, dynamic>;
  final ordered = <String>[];
  final seen = <String>{};
  for (final k in deRaw.keys) {
    if (k == '@@locale' || k.startsWith('@')) continue;
    if (!allKeys.contains(k)) continue;
    ordered.add(k);
    seen.add(k);
  }
  final rest = allKeys.where((k) => !seen.contains(k)).toList()..sort();
  final masterKeys = [...ordered, ...rest];

  for (final e in _locales.entries) {
    final code = e.key;
    final classSuffix = e.value;
    final rawMap = perLocale[code];
    if (rawMap == null) continue;

    final merged = <String, String>{};
    for (final k in masterKeys) {
      final loc = rawMap[k];
      // Leere Strings bewusst erlauben (z. B. time_suffix außerhalb von DE).
      if (loc != null) {
        merged[k] = loc;
      } else {
        merged[k] = deMap[k] ?? '';
      }
    }
    final dartPath =
        root.uri.resolve('lib/l10n/app_localizations_$code.dart').toFilePath();
    File(dartPath).writeAsStringSync(_buildDartFile(
      classSuffix: classSuffix,
      localeCode: code,
      map: merged,
    ));
    stdout.writeln('Wrote $dartPath');
  }
}

String _escapeDartSingleQuoted(String s) {
  return s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\r', r'')
      .replaceAll('\n', r'\n');
}

String _buildDartFile({
  required String classSuffix,
  required String localeCode,
  required Map<String, String> map,
}) {
  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/import_l10n_from_arb.dart — edit l10n/app_$localeCode.arb')
    ..writeln('class AppLocalizations$classSuffix {')
    ..writeln('  static const Map<String, String> translations = {');
  for (final k in map.keys) {
    final v = map[k] ?? '';
    final ek = _escapeDartSingleQuoted(k);
    final ev = _escapeDartSingleQuoted(v);
    buf.writeln("    '$ek': '$ev',");
  }
  buf.writeln('  };');
  buf.writeln('}');
  return buf.toString();
}
