# -*- coding: utf-8 -*-
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
L10N = ROOT / "l10n"

LOCALES = {
    "nl": {
        "dj_quickstart_p_music": "Gasten sturen muziekverzoeken via de wishbox – in de app of op de website. Per feest bepaal je of vooraf-verzoeken zijn toegestaan: gasten kunnen nummers voorstellen vóór de start. Je ziet ze in het feestbeheer tot het feest begint en kunt ze daar controleren.\n\nDe feestbedieningswidget koppelt feest en wishbox: start, pauze en einde op één plek.",
        "dj_quickstart_p_vibesbox": "In de VibesBox verwerk je alle binnenkomende verzoeken. Gewone gastverzoeken komen in Open. Vooraf-verzoeken – indien ingeschakeld – staan eventueel in een vierde tab Vooraf.\n\nJe kunt nummers als gedraaid markeren, afwijzen of verwijderen; verwijderen haalt ze volledig uit de database. Markeer belangrijke open verzoeken met het hart als favoriet.\n\nJe kunt een gast blokkeren via een digitale vingerafdruk van het apparaat. Die is niet 100% uniek – in zeer zeldzame gevallen kunnen meerdere gasten samen geblokkeerd lijken. Je kunt gasten weer deblokkeren.",
        "dj_quickstart_p_free_pro": "Als Free-DJ kun je VibesBox gebruiken – met veel beperkingen (beperkte functies of vergrendelde Pro-features). VibesBox Pro heft die grenzen op en ontgrendelt het volledige pakket – zoals favorieten, geavanceerde bediening en meer DJ-tools zonder Free-limieten.",
        "dj_quickstart_p_checkin": "Check-in en QR-codes leiden gasten naar je feest. De taal voor QR-codes en gedrukte of gedeelde gastteksten kies je apart – onafhankelijk van de taal van je DJ-app.",
        "dj_quickstart_p_qr": "Zodra je een feest aanmaakt, wordt een QR-code voor de wishbox gegenereerd. Je kunt die als afbeelding opslaan, een PDF maken (printen, opslaan, delen) of de directe link met feestcode kopiëren.\n\nBij PDF of afbeelding kies je wat naast de QR verschijnt: locatie (indien ingevuld), login-e-mail, alternatief e-mailadres en telefoonnummer uit je profiel.",
        "dj_quickstart_p_recognition": "Muziekherkenning gebruikt de Shazam-interface. Verkeerd herkende titels of artiesten zijn dus geen VibesBox-fout.\n\nIn Instellingen kun je automatische aanpassing inschakelen (gevoeligheid, drempel) – optioneel, de DJ moet dit aanzetten. Ook automatisch starten van herkenning is daar in te stellen.\n\nHerkende nummers worden in de DJ-app vergeleken met je open lijst en – indien aanwezig – de vooraf-lijst; bij een match gaat het verzoek automatisch naar Gedraaid.\n\nZo ontstaat een geschiedenis van gedraaide nummers die gasten ook zien. De wishbox controleert zelf of een nummer al gedraaid is of al op de open lijst staat – ook als een gast hetzelfde verzoek opnieuw stuurt.\n\nDe indicator voor actieve herkenning (bijv. in de statusbalk) kun je apart in- en uitschakelen.",
        "dj_quickstart_p_i18n": "De bedienstaal van de DJ-app kies je via het wereldbol-icoon – zoals alle gebruikers, niet in het profiel. De DJ-app kan in de taal van jouw keuze draaien.\n\nGasten gebruiken website of app in hun eigen taal; de gastinterface is ook meertalig en de taallijst wordt voortdurend uitgebreid.\n\nAutomatische vertaling van gastgroeten kun je apart in Instellingen in- of uitschakelen – los van de QR- of weergavetaal voor gasten.",
        "dj_quickstart_p_home": "Je DJ-startscherm is flexibel aanpasbaar: je kiest welke widgets en tegels je ziet – zo richt je je overzicht in naar je workflow.",
        "dj_quickstart_p_multidevice": "Je kunt tegelijk op meerdere apparaten inloggen met hetzelfde DJ-account. Muziekherkenning draait echter maar op één apparaat per feest. Om te wisselen, geef het actieve apparaat vrij of neem herkenning over op het nieuwe apparaat zoals in de app aangegeven.",
    },
    "pl": {
        "dj_quickstart_p_music": "Goście wysyłają prośby muzyczne przez wishbox – w aplikacji lub na stronie. Dla każdej imprezy decydujesz, czy dozwolone są prośby z wyprzedzeniem: goście mogą proponować utwory przed startem. Widzisz je w zarządzaniu imprezą do rozpoczęcia i możesz je tam sprawdzić.\n\nWidżet sterowania imprezą łączy imprezę z wishbox: start, pauza i koniec w jednym miejscu.",
        "dj_quickstart_p_vibesbox": "W VibesBox obsługujesz wszystkie przychodzące prośby. Zwykłe trafiają do Otwarte. Prośby z wyprzedzeniem – jeśli włączone – mogą być w czwartej zakładce Wcześniejsze.\n\nMożesz oznaczyć jako zagrane, odrzucić lub usunąć; usunięcie całkowicie usuwa z bazy. Ważne otwarte oznacz sercem jako ulubione.\n\nMożesz zablokować gościa po cyfrowym odcisku urządzenia – nie jest w 100% unikalny; w rzadkich przypadkach kilku gości może wyglądać na zablokowanych. Możesz odblokować.",
        "dj_quickstart_p_free_pro": "Jako DJ Free możesz używać VibesBox – z wieloma ograniczeniami. VibesBox Pro usuwa limity i odblokowuje pełen zestaw funkcji – ulubione, zaawansowane sterowanie i więcej narzędzi DJ bez limitów Free.",
        "dj_quickstart_p_checkin": "Check-in i kody QR prowadzą gości na imprezę. Język QR i drukowanych lub udostępnianych tekstów wybierasz osobno – niezależnie od języka aplikacji DJ.",
        "dj_quickstart_p_qr": "Po utworzeniu imprezy generowany jest QR do wishbox. Możesz zapisać jako obraz, PDF lub skopiować bezpośredni link z kodem imprezy.\n\nPrzy PDF lub obrazie wybierasz, co pokazać obok QR: lokalizację, e-mail logowania, alternatywny e-mail i telefon z profilu.",
        "dj_quickstart_p_recognition": "Rozpoznawanie muzyki korzysta z interfejsu Shazam. Błędnie rozpoznane utwory to nie błąd VibesBox.\n\nW ustawieniach możesz włączyć automatyczne dostosowanie – opcjonalnie, DJ musi to włączyć. Można też włączyć automatyczne uruchamianie rozpoznawania.\n\nRozpoznane utwory są porównywane z listą otwartych i ewentualnie wcześniejszych; przy zgodności prośba przechodzi automatycznie do Zagrane.\n\nPowstaje historia zagranych utworów widoczna dla gości. Wishbox sama sprawdza, czy utwór był już zagrany lub jest na liście otwartych – nawet przy ponownym wysłaniu.\n\nWskaźnik aktywnego rozpoznawania można włączyć osobno.",
        "dj_quickstart_p_i18n": "Język aplikacji DJ wybierasz ikoną globu – nie w profilu. Goście używają strony lub aplikacji w swoim języku; lista języków stale się rozszerza.\n\nAutomatyczne tłumaczenie powitań gości ustawiasz osobno w ustawieniach.",
        "dj_quickstart_p_home": "Ekran główny DJ jest elastyczny: wybierasz widżety i kafelki – przegląd dopasowany do Twojego workflow.",
        "dj_quickstart_p_multidevice": "Możesz logować się jednocześnie na wielu urządzeniach. Rozpoznawanie muzyki działa tylko na jednym urządzeniu na imprezę. Aby zmienić, zwolnij aktywne urządzenie lub przejmij rozpoznawanie na nowym.",
    },
    "cs": {
        "dj_quickstart_p_music": "Hosté posílají hudební přání přes wishbox – v aplikaci nebo na webu. U každé párty rozhodnete, zda jsou povolena předpřání: hosté mohou navrhovat skladby před začátkem. Vidíte je ve správě párty do startu a můžete je kontrolovat.\n\nWidget ovládání párty propojuje párty a wishbox: start, pauza a konec na jednom místě.",
        "dj_quickstart_p_vibesbox": "Ve VibesBox zpracováváte všechna příchozí přání. Běžná jdou do Otevřené. Předpřání – pokud zapnutá – mohou být ve čtvrté záložce Předpřání.\n\nMůžete označit jako přehrané, odmítnout nebo smazat; smazání úplně odstraní z databáze. Důležitá otevřená označte srdcem.\n\nMůžete zablokovat hosta podle digitálního otisku zařízení – není 100% jedinečný; vzácně může být zablokováno více hostů. Lze odblokovat.",
        "dj_quickstart_p_free_pro": "Jako Free DJ můžete používat VibesBox – s mnoha omezeními. VibesBox Pro ruší limity a odemyká plný rozsah – oblíbené, pokročilé ovládání a další nástroje bez Free limitů.",
        "dj_quickstart_p_checkin": "Check-in a QR kódy vedou hosty na párty. Jazyk QR a tiskových textů volíte zvlášť – nezávisle na jazyku DJ aplikace.",
        "dj_quickstart_p_qr": "Po vytvoření párty se vygeneruje QR pro wishbox. Lze uložit jako obrázek, PDF nebo zkopírovat odkaz s kódem párty.\n\nU PDF nebo obrázku zvolíte, co zobrazit vedle QR: místo, e-mail přihlášení, alternativní e-mail a telefon z profilu.",
        "dj_quickstart_p_recognition": "Rozpoznávání hudby používá rozhraní Shazam. Špatně rozpoznané skladby nejsou chyba VibesBox.\n\nV nastavení lze zapnout automatické přizpůsobení – volitelné, DJ musí zapnout. Lze také automatické spuštění rozpoznávání.\n\nRozpoznané skladby se porovnávají s otevřeným a případně předpřáním; při shodě jde přání automaticky do Přehrané.\n\nVzniká historie přehraných skladeb viditelná hostům. Wishbox sama kontroluje, zda skladba už byla přehrána nebo je v otevřeném seznamu – i při opětovném odeslání.\n\nIndikátor aktivního rozpoznávání lze zapnout zvlášť.",
        "dj_quickstart_p_i18n": "Jazyk DJ aplikace volíte ikonou glóbu – ne v profilu. Hosté používají web nebo aplikaci ve svém jazyce; seznam jazyků se stále rozšiřuje.\n\nAutomatický překlad pozdravů hostů nastavíte zvlášť v nastavení.",
        "dj_quickstart_p_home": "Domovská obrazovka DJ je flexibilní: vyberete widgety a dlaždice podle svého workflow.",
        "dj_quickstart_p_multidevice": "Můžete být přihlášeni na více zařízeních současně. Rozpoznávání hudby běží jen na jednom zařízení na párty. Pro změnu uvolněte aktivní zařízení nebo převezměte rozpoznávání na novém.",
    },
    "el": {
        "dj_quickstart_p_music": "Οι καλεσμένοι στέλνουν μουσικά αιτήματα μέσω wishbox – στην εφαρμογή ή στον ιστότοπο. Ανά πάρτι αποφασίζετε αν επιτρέπονται προ-αιτήματα: οι καλεσμένοι προτείνουν κομμάτια πριν την έναρξη. Τα βλέπετε στη διαχείριση πάρτι μέχρι να ξεκινήσει.\n\nΤο widget ελέγχου πάρτι συνδέει πάρτι και wishbox: έναρξη, παύση και τέλος σε ένα σημείο.",
        "dj_quickstart_p_vibesbox": "Στη VibesBox διαχειρίζεστε όλα τα εισερχόμενα αιτήματα. Τα κανονικά πηγαίνουν στο Ανοιχτά. Τα προ-αιτήματα – αν ενεργά – μπορεί να είναι σε τέταρτη καρτέλα.\n\nΜπορείτε να σημειώσετε ως παιγμένο, απόρριψη ή διαγραφή· η διαγραφή αφαιρεί πλήρως από τη βάση. Σημαντικά ανοιχτά με καρδιά ως αγαπημένα.\n\nΜπορείτε να μπλοκάρετε καλεσμένο με ψηφιακό αποτύπωμα συσκευής – όχι 100% μοναδικό· σπάνια πολλοί μπορεί να φαίνονται μπλοκαρισμένοι. Μπορείτε να ξεμπλοκάρετε.",
        "dj_quickstart_p_free_pro": "Ως Free DJ μπορείτε να χρησιμοποιήσετε VibesBox – με πολλούς περιορισμούς. Το VibesBox Pro αφαιρεί τα όρια και ξεκλειδώνει πλήρες σετ – αγαπημένα, προχωρημένος έλεγχος και άλλα εργαλεία DJ.",
        "dj_quickstart_p_checkin": "Το check-in και QR οδηγούν τους καλεσμένους στο πάρτι. Η γλώσσα QR και εκτυπωμένων κειμένων επιλέγεται χωριστά – ανεξάρτητα από τη γλώσσα της εφαρμογής DJ.",
        "dj_quickstart_p_qr": "Με τη δημιουργία πάρτι δημιουργείται QR για wishbox. Μπορείτε αποθήκευση ως εικόνα, PDF ή αντιγραφή συνδέσμου με κωδικό.\n\nΓια PDF ή εικόνα επιλέγετε τι εμφανίζεται δίπλα στο QR: τοποθεσία, email σύνδεσης, εναλλακτικό email και τηλέφωνο από προφίλ.",
        "dj_quickstart_p_recognition": "Η αναγνώριση μουσικής χρησιμοποιεί το Shazam. Λανθασμένα αναγνωρισμένα κομμάτια δεν είναι σφάλμα VibesBox.\n\nΣτις ρυθμίσεις μπορείτε να ενεργοποιήσετε αυτόματη προσαρμογή – προαιρετικά, ο DJ πρέπει να το ενεργοποιήσει. Και αυτόματη εκκίνηση αναγνώρισης.\n\nΤα αναγνωρισμένα συγκρίνονται με ανοιχτή και προ-λίστα· σε ταύτιση πηγαίνουν αυτόματα στο Παιγμένα.\n\nΔημιουργείται ιστορικό παιγμένων που βλέπουν και οι καλεσμένοι. Η wishbox ελέγχει μόνη της αν κομμάτι παίχτηκε ή είναι ανοιχτό – ακόμα και σε δεύτερη αποστολή.\n\nΟ δείκτης ενεργής αναγνώρισης ρυθμίζεται χωριστά.",
        "dj_quickstart_p_i18n": "Η γλώσσα εφαρμογής DJ επιλέγεται με εικονίδιο υδρογείου – όχι στο προφίλ. Οι καλεσμένοι χρησιμοποιούν ιστότοπο ή εφαρμογή στη γλώσσα τους· η λίστα γλωσσών επεκτείνεται συνεχώς.\n\nΗ αυτόματη μετάφραση χαιρετισμών ρυθμίζεται χωριστά.",
        "dj_quickstart_p_home": "Η αρχική οθόνη DJ είναι ευέλικτη: επιλέγετε widgets και πλακίδια για την ροή εργασίας σας.",
        "dj_quickstart_p_multidevice": "Μπορείτε σύνδεση ταυτόχρονα σε πολλές συσκευές. Η αναγνώριση μουσικής τρέχει μόνο σε μία συσκευή ανά πάρτι. Για αλλαγή, απελευθερώστε την ενεργή ή αναλάβετε στην νέα.",
    },
    "hi": {
        "dj_quickstart_p_music": "मेहमान विशबॉक्स के ज़रिए संगीत अनुरोध भेजते हैं – ऐप या वेबसाइट पर। प्रति पार्टी आप तय करते हैं कि पूर्व-अनुरोध अनुमत हैं या नहीं: मेहमान शुरू से पहले गाने सुझा सकते हैं। शुरू होने तक पार्टी प्रबंधन में दिखते हैं।\n\nपार्टी नियंत्रण विजेट पार्टी और विशबॉक्स जोड़ता है: एक जगह से शुरू, रोक और समाप्त।",
        "dj_quickstart_p_vibesbox": "VibesBox में सभी आने वाले अनुरोध संभालें। सामान्य खुले में। पूर्व-अनुरोध – यदि सक्षम – चौथे टैब में।\n\nबजाया, अस्वीकार या हटाएँ; हटाने पर डेटाबेस से पूरी तरह हटता है। महत्वपूर्ण खुले को दिल से पसंदीदा बनाएँ।\n\nमेहमान को डिवाइस फिंगरप्रिंट से ब्लॉक कर सकते हैं – 100% अद्वितीय नहीं; कभी-कभी कई ब्लॉक दिख सकते हैं। अनब्लॉक भी कर सकते हैं।",
        "dj_quickstart_p_free_pro": "Free DJ के रूप में VibesBox उपयोग कर सकते हैं – कई सीमाओं के साथ। VibesBox Pro सीमाएँ हटाता है और पूर्ण सुविधाएँ खोलता है – पसंदीदा, उन्नत नियंत्रण और अधिक DJ टूल।",
        "dj_quickstart_p_checkin": "चेक-इन और QR मेहमानों को पार्टी में ले जाते हैं। QR और मुद्रित भाषा DJ ऐप भाषा से अलग चुनी जाती है।",
        "dj_quickstart_p_qr": "पार्टी बनने पर विशबॉक्स QR बनता है। छवि, PDF या सीधा लिंक कॉपी करें।\n\nPDF/छवि में QR के साथ क्या दिखे: स्थान, लॉगिन ईमेल, वैकल्पिक ईमेल और प्रोफ़ाइल फोन।",
        "dj_quickstart_p_recognition": "संगीत पहचान Shazam इंटरफ़ेस उपयोग करती है। गलत पहचान VibesBox की गलती नहीं।\n\nसेटिंग में स्वचालित समायोजन – वैकल्पिक, DJ चालू करे। स्वचालित सक्रियण भी।\n\nपहचाने गाने खुली और पूर्व-सूची से मिलाए जाते हैं; मेल पर स्वतः बजाया।\n\nबजाए गाने का इतिहास मेहमान भी देखते हैं। विशबॉक्स खुद जाँचती है कि गाना बज चुका है या खुली सूची में है – दोबारा भेजने पर भी।\n\nसक्रिय पहचान संकेतक अलग से टॉगल करें।",
        "dj_quickstart_p_i18n": "DJ ऐप भाषा ग्लोब आइकन से – प्रोफ़ाइल में नहीं। मेहमान अपनी भाषा में साइट/ऐप उपयोग करते हैं; भाषा सूची बढ़ती रहती है।\n\nअभिवादन अनुवाद सेटिंग में अलग से।",
        "dj_quickstart_p_home": "DJ होम स्क्रीन लचीली: विजेट और टाइल चुनें – अपने वर्कफ़्लो के अनुसार।",
        "dj_quickstart_p_multidevice": "एक ही DJ खाते से कई डिवाइस पर एक साथ लॉगिन। संगीत पहचान प्रति पार्टी केवल एक डिवाइस पर। बदलने के लिए सक्रिय डिवाइस छोड़ें या नए पर लें।",
    },
    "vi": {
        "dj_quickstart_p_music": "Khách gửi yêu cầu nhạc qua wishbox – trên app hoặc website. Mỗi tiệc bạn quyết định có cho phép yêu cầu trước: khách gợi ý bài trước khi bắt đầu. Bạn xem trong quản lý tiệc đến khi tiệc bắt đầu.\n\nWidget điều khiển tiệc liên kết tiệc và wishbox: bắt đầu, tạm dừng và kết thúc tại một chỗ.",
        "dj_quickstart_p_vibesbox": "Trong VibesBox xử lý mọi yêu cầu đến. Yêu cầu thường ở Mở. Yêu cầu trước – nếu bật – có thể ở tab thứ tư.\n\nĐánh dấu đã phát, từ chối hoặc xóa; xóa loại bỏ hoàn toàn khỏi cơ sở dữ liệu. Đánh dấu quan trọng bằng trái tim.\n\nCó thể chặn khách bằng dấu vân tay thiết bị – không 100% duy nhất; hiếm khi nhiều khách bị chặn cùng lúc. Có thể bỏ chặn.",
        "dj_quickstart_p_free_pro": "Là DJ Free bạn dùng VibesBox – với nhiều hạn chế. VibesBox Pro gỡ giới hạn và mở đầy đủ tính năng – yêu thích, điều khiển nâng cao và công cụ DJ khác.",
        "dj_quickstart_p_checkin": "Check-in và mã QR dẫn khách vào tiệc. Ngôn ngữ QR và văn bản in/chia sẻ chọn riêng – độc lập với ngôn ngữ app DJ.",
        "dj_quickstart_p_qr": "Khi tạo tiệc sẽ có QR wishbox. Lưu ảnh, PDF hoặc sao chép liên kết có mã tiệc.\n\nKhi tạo PDF/ảnh chọn nội dung bên cạnh QR: địa điểm, email đăng nhập, email thay thế và số điện thoại hồ sơ.",
        "dj_quickstart_p_recognition": "Nhận diện nhạc dùng giao diện Shazam. Nhận diện sai không phải lỗi VibesBox.\n\nTrong cài đặt có thể bật tự điều chỉnh – tùy chọn, DJ phải bật. Cũng có thể bật tự kích hoạt nhận diện.\n\nBài nhận diện so với danh sách mở và trước; khớp thì tự chuyển Đã phát.\n\nLịch sử bài đã phát khách cũng xem được. Wishbox tự kiểm tra bài đã phát hoặc đang mở – kể cả khi khách gửi lại.\n\nChỉ báo nhận diện đang hoạt động bật/tắt riêng.",
        "dj_quickstart_p_i18n": "Ngôn ngữ app DJ chọn bằng biểu tượng quả địa cầu – không trong hồ sơ. Khách dùng web/app bằng ngôn ngữ của họ; danh sách ngôn ngữ mở rộng liên tục.\n\nDịch lời chào khách cài riêng trong cài đặt.",
        "dj_quickstart_p_home": "Màn hình chính DJ linh hoạt: chọn widget và ô theo quy trình làm việc.",
        "dj_quickstart_p_multidevice": "Đăng nhập đồng thời nhiều thiết bị cùng tài khoản DJ. Nhận diện nhạc chỉ chạy trên một thiết bị mỗi tiệc. Đổi thiết bị theo hướng dẫn trong app.",
    },
    "sq": {
        "dj_quickstart_p_music": "Mysafirët dërgojnë kërkesa muzikore përmes wishbox – në aplikacion ose në faqe. Për çdo festë vendos nëse lejohen parakërkesat: mysafirët propozojnë këngë para fillimit. I sheh në menaxhimin e festës deri në start.\n\nWidget-i i kontrollit lidh festën dhe wishbox: nisje, pauzë dhe fund në një vend.",
        "dj_quickstart_p_vibesbox": "Në VibesBox përpunon të gjitha kërkesat. Të rregulltat shkojnë te Hapura. Parakërkesat – nëse aktiv – mund të jenë në skedën e katërt.\n\nMund t’i shënosh si luajtur, refuzuar ose fshirë; fshirja i heq plotësisht nga baza. Të rëndësishmet me zemër si të preferuara.\n\nMund të bllokosh mysafir me gjurmë dixhitale të pajisjes – jo 100% unike; rrallë mund të bllokohen disa së bashku. Mund t’i zhbllokosh.",
        "dj_quickstart_p_free_pro": "Si DJ Free përdor VibesBox – me shumë kufizime. VibesBox Pro heq kufijtë dhe hap funksione të plota – të preferuar, kontroll të avancuar dhe më shumë.",
        "dj_quickstart_p_checkin": "Check-in dhe QR udhëheqin mysafirët në festë. Gjuha e QR dhe teksteve të printuara zgjidhet veçmas – pavarësisht nga gjuha e aplikacionit DJ.",
        "dj_quickstart_p_qr": "Kur krijohet festa gjenerohet QR për wishbox. Ruaj si imazh, PDF ose kopjo lidhjen me kod feste.\n\nPër PDF/imazh zgjidh çfarë shfaqet pranë QR: vendndodhja, email hyrjeje, email alternativ dhe telefon nga profili.",
        "dj_quickstart_p_recognition": "Njohja e muzikës përdor ndërfaqen Shazam. Këngët e gabuara nuk janë gabim i VibesBox.\n\nNë cilësime mund të aktivizosh përshtatje automatike – opsionale, DJ duhet ta ndezë. Edhe aktivizim automatik i njohjes.\n\nKëngët e njohura krahasohen me listën e hapur dhe parakërkesat; përputhje → automatikisht Luajtur.\n\nKrijohet histori e këngëve të luajtura që e shohin edhe mysafirët. Wishbox kontrollon vetë nëse kënga u luajt ose është e hapur – edhe në dërgim të dytë.\n\nTreguesi i njohjes aktive ndizet veçmas.",
        "dj_quickstart_p_i18n": "Gjuha e aplikacionit DJ zgjidhet me ikonën e globit – jo në profil. Mysafirët përdorin faqen/aplikacionin në gjuhën e tyre; lista e gjuhëve zgjerohet vazhdimisht.\n\nPërkthimi automatik i përshëndetjeve vendoset veçmas në cilësime.",
        "dj_quickstart_p_home": "Faqja kryesore DJ është fleksibël: zgjidh widget-et dhe pllakat sipas rrjedhës së punës.",
        "dj_quickstart_p_multidevice": "Mund të hysh njëkohësisht në disa pajisje me të njëjtin llogari DJ. Njohja e muzikës funksionon vetëm në një pajisje për festë. Për ndërrim, lësho pajisjen aktive ose merr njohjen në të renë.",
    },
    "ja": {
        "dj_quickstart_p_music": "ゲストはウィッシュボックス経由でリクエストを送信します（アプリまたはサイト）。パーティーごとに事前リクエストの可否を決められます。開始前はパーティー管理で確認できます。\n\nパーティー操作ウィジェットでウィッシュボックスの開始・一時停止・終了を一括管理します。",
        "dj_quickstart_p_vibesbox": "VibesBoxで届いたリクエストを処理します。通常は「未処理」、事前リクエストは有効時に第4タブに表示される場合があります。\n\n再生済み・拒否・削除が可能で、削除はDBから完全に消えます。重要な未処理はハートでお気に入りに。\n\nゲストは端末フィンガープリントでブロック可能（100%一意ではなく、稀に複数が同時にブロック表示されることも）。解除も可能です。",
        "dj_quickstart_p_free_pro": "Free DJでもVibesBoxを利用できますが、多くの制限があります。VibesBox Proで制限が解除され、お気に入りや高度な操作など全機能が使えます。",
        "dj_quickstart_p_checkin": "チェックインとQRでゲストをパーティーへ誘導。QR・印刷文の言語はDJアプリの言語とは別に選択します。",
        "dj_quickstart_p_qr": "パーティー作成時にウィッシュボックス用QRが生成されます。画像保存、PDF、パーティーコード付きリンクのコピーが可能です。\n\nPDF/画像ではQR横に表示する内容（場所、ログインメール、代替メール、プロフィールの電話）を選べます。",
        "dj_quickstart_p_recognition": "音楽認識はShazamインターフェースを使用。誤認識はVibesBoxの不具合ではありません。\n\n設定で自動調整（感度・閾値）を任意で有効化できます。自動起動も設定可能です。\n\n認識曲は未処理リストと事前リストと照合し、一致時は自動で「再生済み」へ。\n\n再生履歴はゲストも閲覧可能。ウィッシュボックスが既再生・未処理の重複を自動チェック（再送信時も）。\n\n認識中インジケーターは個別にオン/オフ可能。",
        "dj_quickstart_p_i18n": "DJアプリの言語は地球アイコンで選択（プロフィールではありません）。ゲストは各自の言語でサイト/アプリを利用。言語リストは随時拡充。\n\nゲスト挨拶の自動翻訳は設定で個別に切り替え。",
        "dj_quickstart_p_home": "DJホーム画面はカスタマイズ可能。表示するウィジェットとタイルを選択できます。",
        "dj_quickstart_p_multidevice": "同一DJアカウントで複数端末に同時ログイン可能ですが、音楽認識はパーティーあたり1端末のみ。切り替えはアプリの表示に従い解放または引き継ぎ。",
    },
    "ar": {
        "dj_quickstart_p_music": "يرسل الضيوف طلبات الموسيقى عبر صندوق الأمنيات – في التطبيق أو على الموقع. لكل حفلة تقرر ما إذا كانت الأمنيات المسبقة مسموحة: يمكن للضيوف اقتراح أغانٍ قبل البداية. تراها في إدارة الحفلة حتى البدء.\n\nأداة التحكم بالحفلة تربط الحفلة وصندوق الأمنيات: بدء وإيقاف مؤقت وإنهاء من مكان واحد.",
        "dj_quickstart_p_vibesbox": "في VibesBox تتعامل مع جميع الطلبات الواردة. الطلبات العادية في «مفتوحة». الأمنيات المسبقة – إن فُعلت – قد تكون في تبويب رابع.\n\nيمكن وضع علامة مُشغَّل أو رفض أو حذف؛ الحذف يزيلها كلياً من قاعدة البيانات. الأهم بالقلب كمفضلة.\n\nيمكن حظر ضيف ببصمة رقمية للجهاز – ليست فريدة 100%؛ نادراً قد يُحظر أكثر من ضيف معاً. يمكن إلغاء الحظر.",
        "dj_quickstart_p_free_pro": "كـ DJ مجاني يمكنك استخدام VibesBox – مع قيود كثيرة. VibesBox Pro يرفع القيود ويفتح الميزات الكاملة – المفضلة والتحكم المتقدم وأدوات DJ أخرى.",
        "dj_quickstart_p_checkin": "تسجيل الوصول ورموز QR يوجّهان الضيوف للحفلة. لغة QR والنصوص المطبوعة تُختار بشكل منفصل – بغض النظر عن لغة تطبيق DJ.",
        "dj_quickstart_p_qr": "عند إنشاء حفلة يُنشأ QR لصندوق الأمنيات. يمكن الحفظ كصورة أو PDF أو نسخ الرابط مع رمز الحفلة.\n\nعند PDF/صورة تختار ما يظهر بجانب QR: الموقع والبريد وبديله والهاتف من الملف الشخصي.",
        "dj_quickstart_p_recognition": "التعرف على الموسيقى يستخدم واجهة Shazam. الأخطاء ليست خطأ VibesBox.\n\nفي الإعدادات يمكن تفعيل التكيف التلقائي – اختياري ويجب على DJ تفعيله. وتفعيل تلقائي للتعرف.\n\nالأغاني المُعرَّفة تُقارن بالقائمة المفتوحة والمسبقة؛ عند التطابق تنتقل تلقائياً إلى «مُشغَّل».\n\nيُبنى سجل للأغاني المُشغَّلة يراه الضيوف أيضاً. صندوق الأمنيات يتحقق بنفسه إن كانت الأغنية مُشغَّلة أو في القائمة المفتوحة – حتى عند الإرسال مرة ثانية.\n\nمؤشر التعرف النشط يُفعَّل بشكل منفصل.",
        "dj_quickstart_p_i18n": "لغة تطبيق DJ تُختار بأيقونة الكرة الأرضية – ليس في الملف الشخصي. الضيوف يستخدمون الموقع/التطبيق بلغتهم؛ قائمة اللغات تتوسع باستمرار.\n\nترجمة التحيات تُضبط منفصلة في الإعدادات.",
        "dj_quickstart_p_home": "الشاشة الرئيسية للـ DJ قابلة للتخصيص: تختار الودجات والبلاطات حسب سير عملك.",
        "dj_quickstart_p_multidevice": "يمكنك تسجيل الدخول على عدة أجهزة في آن واحد. التعرف على الموسيقى يعمل على جهاز واحد فقط لكل حفلة. للتبديل حرّر الجهاز النشط أو انقل التعرف كما في التطبيق.",
    },
}

for code, updates in LOCALES.items():
    path = L10N / f"app_{code}.arb"
    data = json.loads(path.read_text(encoding="utf-8"))
    data.update(updates)
    path.write_text(json.dumps(data, ensure_ascii=False, indent="\t") + "\n", encoding="utf-8")
    print(f"Updated {path.name}")
